### ISSUE TITLE
available in registry?

### ISSUE THREAD

**Issue by waynedpj** [jonschlinkert/yfm#2]
i had some odd behavior with Assemble and i made the mistake of doing an `npm update`!  now my project is broken and i cannot get Assemble and company reinstalled.  i have removed `node_modules` and cleaned the npm cache but i keep getting the following error when trying to install a helper i use:

```
npm i --save-dev handlebars-helper-compose
npm WARN package.json in-giro.org@0.1.4 No README data
npm http GET https://registry.npmjs.org/handlebars-helper-compose
npm http 304 https://registry.npmjs.org/handlebars-helper-compose
npm http GET https://registry.npmjs.org/yfm
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/marked-extras
npm http GET https://registry.npmjs.org/fs-utils
npm http 404 https://registry.npmjs.org/yfm
npm http 304 https://registry.npmjs.org/marked
npm ERR! 404 'yfm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.17-gentoo-gnu
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "--save-dev" "handlebars-helper-compose"
npm ERR! cwd /home/waynedpj/progetti/in-giro.org
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! code E404
npm http 304 https://registry.npmjs.org/marked-extras
npm http 304 https://registry.npmjs.org/fs-utils
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/waynedpj/progetti/in-giro.org/npm-debug.log
npm ERR! not ok code 0
```

trying to install `yfm` directly also fails:

```
$ npm i --save-dev yfm
npm WARN package.json in-giro.org@0.1.4 No README data
npm http GET https://registry.npmjs.org/yfm
npm http 404 https://registry.npmjs.org/yfm
npm ERR! 404 'yfm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.17-gentoo-gnu
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "--save-dev" "yfm"
npm ERR! cwd /home/waynedpj/progetti/in-giro.org
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/waynedpj/progetti/in-giro.org/npm-debug.log
npm ERR! not ok code 0
```

perhaps my installation is hosed but i wanted to do a sanity check first.

thanks in advance

**Comment by waynedpj** [comment]
PS. when visiting https://npmjs.org/package/yfm i get the following error:

```
Not Found

An error occurred. If you feel this is a bug (which is likely), you are encouraged to submit an issue so that it can be addressed.

If you have ideas about how this could have been handled better, please share those as well.
Additional Debug Information

Error: Not Found
    at ServerResponse.error (/home/node/npm-www/node_modules/error-page/error-page.js:108:20)
    at MC.ondone (/home/node/npm-www/routes/package-page.js:31:53)
    at MC.next (/home/node/npm-www/node_modules/emcee/emcee.js:45:12)
    at /home/node/npm-www/models/browse.js:151:7
    at Array.forEach (native)
    at /home/node/npm-www/models/browse.js:150:9
    at saved (/home/node/npm-www/node_modules/npm-registry-client/lib/get.js:138:7)
    at Object.oncomplete (fs.js:107:15)

headers = {
  "host": "npmjs.org",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0",
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  "accept-language": "en-us,en;q=0.7,it;q=0.3",
  "accept-encoding": "gzip, deflate",
  "dnt": "1",
  "referer": "https://npmjs.org/package/handlebars-helper-compose",
  "connection": "keep-alive"
}

error = undefined

statusCode = 404

stamp = pid=49021 worker=16 6245cfe3b6e6acb74dbdd686d3709cd666118
```

perhaps this is all an NPM problem?

**Comment by doowb** [comment]
I was running into an issue earlier. I don't think it's on npm. I'll get it up there soon.

**Comment by jonschlinkert** [comment]
Strange, when I was trying to push up the latest version I was getting strange errors, then it "went through". Apparently not.

**Comment by doowb** [comment]
That might have been the time when npm was having a lot of issues. I was seeing "missing" repos too.

**Comment by waynedpj** [comment]
@doowb @jonschlinkert OK, thanks.  if you have the time, please just drop a line when you push it back up.

**Comment by doowb** [comment]
I pushed it up, but the compose helper depends on version 0.1.0 and yfm is at 0.2.0. I'm not sure what happened to the previous versions.

I'm working on updating the compose helper, but I'm running into a stack size exceed error. I'm not sure what's causing it.

**Comment by jonschlinkert** [comment]
> I'm not sure what happened to the previous versions.

That's strange. I had a package completely disappear from npm a couple weeks ago ("components"), I had to recover it from someone else. I'll try to push up a 0.1.0 version in a minute and see if that resolves it

**Comment by lukeapage** [comment]
yeh just came across this on less-docs - 0.1 is missing from the registry still.
I had problems with npm publishing but it turned out it was fixed by upgrading to the very latest npm and node.
I would recommend upgrading locally, ubpublishing 0.2, publishing 0.1 and then publishing 0.2 again.

**Comment by lukeapage** [comment]
p.s. even after upgrading less-docs package it still fails because fs-utils references 0.1 of yfm

**Comment by jonschlinkert** [comment]
no, I know why I can't publish to this repo now! lol @doowb when you published 2.0 you didn't re-add me as a maintainer!

**Comment by doowb** [comment]
added... sorry.

**Comment by jonschlinkert** [comment]
lol np

**Comment by ain** [comment]
The project could also use the [release tags](https://github.com/assemble/yfm/releases) :)
